/**
 * Parity: the JS evaluator must reproduce the Python LightGBM predictions for the ICU-need model.
 * Fixture generated by ml/scripts/export_js_models.py (3000 random patients incl. missing values).
 */
const cases = require('./fixtures/icu_need_parity.json');
const { predictIcuNeed, buildFeatures, getModel } = require('../src/ml/icuNeed');
const { rawScore, contributions, transform } = require('../src/ml/lightgbm');

const toInput = (c) => ({
  age: c.age,
  gender: c.gender,
  acuity: c.acuity_level,
  priority: c.priority,
  requiresOt: Boolean(c.requires_ot),
  requiresDiagnostic: Boolean(c.requires_diagnostic),
  diagnosticType: c.diagnostic_type,
  arrivalTime: new Date(c.arrival_time), // naive ISO -> local time, like pandas
});

describe('ICU-need model (LightGBM -> JS)', () => {
  test('matches Python predictions on all parity cases', () => {
    const model = getModel();
    let maxDiff = 0;
    for (const c of cases) {
      const p = transform(model, rawScore(model, buildFeatures(toInput(c))));
      maxDiff = Math.max(maxDiff, Math.abs(p - c.expected));
    }
    expect(cases.length).toBeGreaterThan(1000);
    expect(maxDiff).toBeLessThan(1e-9);
  });

  test('path contributions add up to the raw score', () => {
    const model = getModel();
    for (const c of cases.slice(0, 200)) {
      const x = buildFeatures(toInput(c));
      const { bias, contrib } = contributions(model, x);
      const total = bias + contrib.reduce((a, b) => a + b, 0);
      expect(Math.abs(total - rawScore(model, x))).toBeLessThan(1e-9);
    }
  });

  test('clinically sensible ordering and output shape', () => {
    const at = new Date('2026-10-05T10:00:00');
    const critical = predictIcuNeed({ age: 74, gender: 'Male', acuity: 1, arrivalTime: at });
    const minor = predictIcuNeed({ age: 30, gender: 'Female', acuity: 4, arrivalTime: at });
    expect(critical.probability).toBeGreaterThan(0.8);
    expect(critical.needsIcu).toBe(true);
    expect(critical.level).toBe('high');
    expect(minor.probability).toBeLessThan(0.05);
    expect(minor.needsIcu).toBe(false);
    expect(critical.factors.length).toBeGreaterThan(0);
    expect(critical.factors[0]).toEqual(expect.objectContaining({ factor: expect.any(String), direction: 'up' }));
  });

  test('handles unknown age and gender', () => {
    const r = predictIcuNeed({ acuity: 2, arrivalTime: new Date() });
    expect(r.probability).toBeGreaterThanOrEqual(0);
    expect(r.probability).toBeLessThanOrEqual(1);
  });
});
